package robotics.hutu.joycontrol;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import robotics.hutu.joycontrol.Controller;
import robotics.hutu.joycontrol.Profile;

import robotics.hutu.joycontrol.ControllerDao;
import robotics.hutu.joycontrol.ProfileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig controllerDaoConfig;
    private final DaoConfig profileDaoConfig;

    private final ControllerDao controllerDao;
    private final ProfileDao profileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        controllerDaoConfig = daoConfigMap.get(ControllerDao.class).clone();
        controllerDaoConfig.initIdentityScope(type);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        controllerDao = new ControllerDao(controllerDaoConfig, this);
        profileDao = new ProfileDao(profileDaoConfig, this);

        registerDao(Controller.class, controllerDao);
        registerDao(Profile.class, profileDao);
    }
    
    public void clear() {
        controllerDaoConfig.clearIdentityScope();
        profileDaoConfig.clearIdentityScope();
    }

    public ControllerDao getControllerDao() {
        return controllerDao;
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

}
